spring:
  application:
    name: authentication-service
  redis:
    host: redis
  cloud:
    stream:
      bindings:
        authentication_request:
          destination: queue.authentication.request.events
          binder: docker_rabbit
        authentication_response:
          destination: queue.authentication.response.events
          binder: docker_rabbit
      binders:
        docker_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit
                port: 5672
                #username: guest
                #password: guest
                virtual-host: /
server:
  port: 8087

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/