spring:
  application:
    name: bank
  data:
    mongodb:
      host: mongo
      port: 27017
      database: bank-database
      username: admin
      password: password
  cloud:
    stream:
      bindings:
        tx_authorization_response:
          destination: queue.txauthorization.response.events
          binder: docker_rabbit
        authentication_response:
          destination: queue.authentication.response.events
          binder: docker_rabbit
      binders:
        docker_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit
                port: 5672
                #username: guest
                #password: guest
                virtual-host: /
server:
  port: 8083

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/