spring:
  application:
    name: bank
  data:
    mongodb:
      host: mongo
      port: 27017
      database: bank-database
      username: admin
      password: password

server:
  port: 8083

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/