spring:
  application:
    name: discovery
  redis:
    host: localhost
    port: 6379
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

