
spring:
  application:
    name: gateway
server:
  port: 8082

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    bank-service:
      path: /bank-service/**
      sensitive-headers: Set-Cookie,Authorization
    discovery:
      path: /discovery/**
      url: http://localhost:8761
      sensitive-headers: Set-Cookie,Authorization
hystrix:
  command:
    bank-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
